name: Release Go project

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
